#!/usr/bin/env python

# A simple python script that takes in a lenght of time in seconds, a number of beats per measure, and a bpm and spits out a number of bars that fits.

import sys

def time_to_measures(time_in_seconds, beats_per_measure, beats_per_minute):
    number_of_measures = ((time_in_seconds * (beats_per_minute / 60)) / beats_per_measure)
    return number_of_measures
    
    


while __name__ == "__main__":

    if len(sys.argv) < 4:
        print("Not enough data. Format: {len time in seconds} {beats per measure} {beats per minute}")
        break 
    else:
        time_in_seconds = int(sys.argv[1])
        beats_per_measure = int(sys.argv[2])
        beats_per_minute = int(sys.argv[3])
        number_of_measures = time_to_measures(time_in_seconds, beats_per_measure, beats_per_minute)

        print("You need {} bars in {}".format(number_of_measures, beats_per_measure))
        break

